# Official MySQL image
FROM mysql:latest

# ENVs for MySQL
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=app_user
ENV MYSQL_PASSWORD=1234

# Port 3306 for MySQL
EXPOSE 3306

# Set the volume
VOLUME /var/lib/mysql