name: Build Images

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image for App
      run: docker build . --tag task:${{ github.actor }}

    - name: Build the Docker image for MySQL
      run: docker build . -f Dockerfile.mysql --tag task:${{ github.actor }}
